/* tslint:disable */
/* eslint-disable */
/**
 * IPCameras API
 * IPCameras API API
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: nathanfaucett@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface P2PAccess
 */
export interface P2PAccess {
    /**
     * 
     * @type {string}
     * @memberof P2PAccess
     */
    host: string;
    /**
     * 
     * @type {string}
     * @memberof P2PAccess
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof P2PAccess
     */
    password: string;
    /**
     * 
     * @type {boolean}
     * @memberof P2PAccess
     */
    ssl: boolean;
}

/**
 * Check if a given object implements the P2PAccess interface.
 */
export function instanceOfP2PAccess(value: object): boolean {
    if (!('host' in value)) return false;
    if (!('id' in value)) return false;
    if (!('password' in value)) return false;
    if (!('ssl' in value)) return false;
    return true;
}

export function P2PAccessFromJSON(json: any): P2PAccess {
    return P2PAccessFromJSONTyped(json, false);
}

export function P2PAccessFromJSONTyped(json: any, ignoreDiscriminator: boolean): P2PAccess {
    if (json == null) {
        return json;
    }
    return {
        
        'host': json['host'],
        'id': json['id'],
        'password': json['password'],
        'ssl': json['ssl'],
    };
}

export function P2PAccessToJSON(value?: P2PAccess | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'host': value['host'],
        'id': value['id'],
        'password': value['password'],
        'ssl': value['ssl'],
    };
}

