/* tslint:disable */
/* eslint-disable */
/**
 * IPCameras API
 * IPCameras API API
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: nathanfaucett@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ResetPassword
 */
export interface ResetPassword {
    /**
     * 
     * @type {string}
     * @memberof ResetPassword
     */
    password: string;
    /**
     * 
     * @type {string}
     * @memberof ResetPassword
     */
    passwordConfirmation: string;
}

/**
 * Check if a given object implements the ResetPassword interface.
 */
export function instanceOfResetPassword(value: object): boolean {
    if (!('password' in value)) return false;
    if (!('passwordConfirmation' in value)) return false;
    return true;
}

export function ResetPasswordFromJSON(json: any): ResetPassword {
    return ResetPasswordFromJSONTyped(json, false);
}

export function ResetPasswordFromJSONTyped(json: any, ignoreDiscriminator: boolean): ResetPassword {
    if (json == null) {
        return json;
    }
    return {
        
        'password': json['password'],
        'passwordConfirmation': json['passwordConfirmation'],
    };
}

export function ResetPasswordToJSON(value?: ResetPassword | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'password': value['password'],
        'passwordConfirmation': value['passwordConfirmation'],
    };
}

