/* tslint:disable */
/* eslint-disable */
/**
 * IPCameras API
 * IPCameras API API
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: nathanfaucett@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Token
 */
export interface Token {
    /**
     * 
     * @type {string}
     * @memberof Token
     */
    accessToken: string;
    /**
     * 
     * @type {number}
     * @memberof Token
     */
    expiresIn: number;
    /**
     * 
     * @type {string}
     * @memberof Token
     */
    issuedTokenType: string;
    /**
     * 
     * @type {string}
     * @memberof Token
     */
    refreshToken: string;
    /**
     * 
     * @type {number}
     * @memberof Token
     */
    refreshTokenExpiresIn: number;
    /**
     * 
     * @type {string}
     * @memberof Token
     */
    tokenType: string;
}

/**
 * Check if a given object implements the Token interface.
 */
export function instanceOfToken(value: object): boolean {
    if (!('accessToken' in value)) return false;
    if (!('expiresIn' in value)) return false;
    if (!('issuedTokenType' in value)) return false;
    if (!('refreshToken' in value)) return false;
    if (!('refreshTokenExpiresIn' in value)) return false;
    if (!('tokenType' in value)) return false;
    return true;
}

export function TokenFromJSON(json: any): Token {
    return TokenFromJSONTyped(json, false);
}

export function TokenFromJSONTyped(json: any, ignoreDiscriminator: boolean): Token {
    if (json == null) {
        return json;
    }
    return {
        
        'accessToken': json['accessToken'],
        'expiresIn': json['expiresIn'],
        'issuedTokenType': json['issuedTokenType'],
        'refreshToken': json['refreshToken'],
        'refreshTokenExpiresIn': json['refreshTokenExpiresIn'],
        'tokenType': json['tokenType'],
    };
}

export function TokenToJSON(value?: Token | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'accessToken': value['accessToken'],
        'expiresIn': value['expiresIn'],
        'issuedTokenType': value['issuedTokenType'],
        'refreshToken': value['refreshToken'],
        'refreshTokenExpiresIn': value['refreshTokenExpiresIn'],
        'tokenType': value['tokenType'],
    };
}

