apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "ipcameras_ui.fullname" . }}-environment
  labels:
    {{- include "ipcameras_ui.labels" . | nindent 4 }}
data:
{{ toYaml .Values.env | indent 2 }}
