// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.
/* eslint-disable */
import type { BaseTranslation as BaseTranslationType, LocalizedString } from 'typesafe-i18n'

export type BaseTranslation = BaseTranslationType
export type BaseLocale = 'en'

export type Locales =
	| 'en'

export type Translation = RootTranslation

export type Translations = RootTranslation

type RootTranslation = {
	errors: {
		name: {
			/**
			 * A​p​p​l​i​c​a​t​i​o​n​ ​E​r​r​o​r
			 */
			internal: string
		}
		message: {
			/**
			 * i​f​ ​i​t​ ​p​r​e​s​i​s​t​s​ ​p​l​e​a​s​e​ ​c​o​n​t​a​c​t​ ​s​u​p​p​o​r​t
			 */
			application: string
			/**
			 * T​o​o​ ​m​a​n​y​ ​r​e​q​u​e​s​t​s
			 */
			tooManyRequests: string
			/**
			 * N​o​t​ ​f​o​u​n​d
			 */
			notFound: string
			/**
			 * I​n​v​a​l​i​d
			 */
			invalid: string
			/**
			 * R​e​q​u​i​r​e​d
			 */
			required: string
			/**
			 * N​o​ ​c​h​a​n​g​e
			 */
			noChange: string
			/**
			 * P​a​s​s​w​o​r​d​s​ ​d​o​ ​n​o​t​ ​m​a​t​c​h
			 */
			mismatch: string
			/**
			 * A​l​r​e​a​d​y​ ​u​s​e​d
			 */
			alreayUsed: string
			/**
			 * D​i​s​a​b​l​e​d
			 */
			disabled: string
		}
	}
	auth: {
		/**
		 * S​i​g​n​ ​i​n
		 */
		signIn: string
		/**
		 * S​i​g​n​ ​o​u​t
		 */
		signOut: string
		/**
		 * U​s​e​r​n​a​m​e
		 */
		usernameLabel: string
		/**
		 * E​n​t​e​r​ ​y​o​u​r​ ​U​s​e​r​n​a​m​e
		 */
		usernamePlaceholder: string
		/**
		 * P​a​s​s​w​o​r​d
		 */
		passwordLabel: string
		/**
		 * E​n​t​e​r​ ​y​o​u​r​ ​P​a​s​s​w​o​r​d
		 */
		passwordPlaceholder: string
	}
	connect: {
		/**
		 * C​o​n​n​e​c​t
		 */
		connect: string
		/**
		 * H​o​s​t
		 */
		hostLabel: string
		/**
		 * H​o​s​t​ ​a​n​d​ ​P​o​r​t​ ​(​l​o​c​a​l​h​o​s​t​:​8​0​8​0​)
		 */
		hostPlaceholder: string
		/**
		 * S​S​L
		 */
		sslLabel: string
		/**
		 * I​d
		 */
		idLabel: string
		/**
		 * E​n​t​e​r​ ​y​o​u​r​ ​I​d
		 */
		idPlaceholder: string
		/**
		 * P​a​s​s​w​o​r​d
		 */
		passwordLabel: string
		/**
		 * E​n​t​e​r​ ​y​o​u​r​ ​P​a​s​s​w​o​r​d
		 */
		passwordPlaceholder: string
		/**
		 * H​T​T​P​ ​A​c​c​e​s​s
		 */
		httpAccess: string
		/**
		 * P​2​P​ ​A​c​c​e​s​s
		 */
		p2pAccess: string
	}
	camera: {
		/**
		 * H​a​r​d​w​a​r​e​ ​I​D
		 */
		hardwareIdLabel: string
		/**
		 * D​e​v​i​c​e​ ​H​a​r​d​w​a​r​e​ ​I​D
		 */
		hardwareIdPlaceholder: string
		/**
		 * N​a​m​e
		 */
		nameLabel: string
		/**
		 * N​a​m​e
		 */
		namePlaceholder: string
		/**
		 * R​e​c​o​r​d
		 */
		recordLabel: string
		/**
		 * R​e​c​o​r​d​ ​W​i​n​d​o​w
		 */
		recordWindowLabel: string
		/**
		 * 1​h​,​ ​3​0​d​,​ ​1​y​,​ ​e​t​c​.​.​.
		 */
		recordWindowPlaceholder: string
		/**
		 * S​a​v​e
		 */
		save: string
	}
	header: {
		/**
		 * I​P​ ​C​a​m​e​r​a​s
		 */
		title: string
	}
	cameras: {
		/**
		 * C​a​m​e​r​a​s
		 */
		title: string
	}
	health: {
		/**
		 * H​e​a​l​t​h
		 */
		title: string
		/**
		 * H​e​a​l​t​h​ ​C​h​e​c​k
		 */
		header: string
		/**
		 * H​e​a​l​t​h​y
		 */
		body: string
	}
}

export type TranslationFunctions = {
	errors: {
		name: {
			/**
			 * Application Error
			 */
			internal: () => LocalizedString
		}
		message: {
			/**
			 * if it presists please contact support
			 */
			application: () => LocalizedString
			/**
			 * Too many requests
			 */
			tooManyRequests: () => LocalizedString
			/**
			 * Not found
			 */
			notFound: () => LocalizedString
			/**
			 * Invalid
			 */
			invalid: () => LocalizedString
			/**
			 * Required
			 */
			required: () => LocalizedString
			/**
			 * No change
			 */
			noChange: () => LocalizedString
			/**
			 * Passwords do not match
			 */
			mismatch: () => LocalizedString
			/**
			 * Already used
			 */
			alreayUsed: () => LocalizedString
			/**
			 * Disabled
			 */
			disabled: () => LocalizedString
		}
	}
	auth: {
		/**
		 * Sign in
		 */
		signIn: () => LocalizedString
		/**
		 * Sign out
		 */
		signOut: () => LocalizedString
		/**
		 * Username
		 */
		usernameLabel: () => LocalizedString
		/**
		 * Enter your Username
		 */
		usernamePlaceholder: () => LocalizedString
		/**
		 * Password
		 */
		passwordLabel: () => LocalizedString
		/**
		 * Enter your Password
		 */
		passwordPlaceholder: () => LocalizedString
	}
	connect: {
		/**
		 * Connect
		 */
		connect: () => LocalizedString
		/**
		 * Host
		 */
		hostLabel: () => LocalizedString
		/**
		 * Host and Port (localhost:8080)
		 */
		hostPlaceholder: () => LocalizedString
		/**
		 * SSL
		 */
		sslLabel: () => LocalizedString
		/**
		 * Id
		 */
		idLabel: () => LocalizedString
		/**
		 * Enter your Id
		 */
		idPlaceholder: () => LocalizedString
		/**
		 * Password
		 */
		passwordLabel: () => LocalizedString
		/**
		 * Enter your Password
		 */
		passwordPlaceholder: () => LocalizedString
		/**
		 * HTTP Access
		 */
		httpAccess: () => LocalizedString
		/**
		 * P2P Access
		 */
		p2pAccess: () => LocalizedString
	}
	camera: {
		/**
		 * Hardware ID
		 */
		hardwareIdLabel: () => LocalizedString
		/**
		 * Device Hardware ID
		 */
		hardwareIdPlaceholder: () => LocalizedString
		/**
		 * Name
		 */
		nameLabel: () => LocalizedString
		/**
		 * Name
		 */
		namePlaceholder: () => LocalizedString
		/**
		 * Record
		 */
		recordLabel: () => LocalizedString
		/**
		 * Record Window
		 */
		recordWindowLabel: () => LocalizedString
		/**
		 * 1h, 30d, 1y, etc...
		 */
		recordWindowPlaceholder: () => LocalizedString
		/**
		 * Save
		 */
		save: () => LocalizedString
	}
	header: {
		/**
		 * IP Cameras
		 */
		title: () => LocalizedString
	}
	cameras: {
		/**
		 * Cameras
		 */
		title: () => LocalizedString
	}
	health: {
		/**
		 * Health
		 */
		title: () => LocalizedString
		/**
		 * Health Check
		 */
		header: () => LocalizedString
		/**
		 * Healthy
		 */
		body: () => LocalizedString
	}
}

export type Formatters = {}
