replicas:
  min: 1
  max: 8
  resource:
    cpu:
      utilization: 80
    memory:
      utilization: 90
  scaleDown:
    stabilizationWindowSeconds: 30
  scaleUp:
    stabilizationWindowSeconds: 15

image:
  repository: ghcr.io/aicacia/ipcameras-api
  tag: latest
  pullPolicy: Always
  pullSecrets: github-registry
  hash: sha256:13ba025b6c186da3fdce3db68f192721fef8300ae02f2ae76c953d771b7180e4

env:
  DATABASE_URL: "postgresql://postgres:postgres@localhost/ipcameras_prod?pool=20"

ingress:
  enabled: true
  ingressClassName: nginx
  annotations:
    kubernetes.io/tls-acme: "true"
    cert-manager.io/cluster-issuer: letsencrypt
    nginx.ingress.kubernetes.io/proxy-body-size: "10m"
  hosts:
    - host: api.aicacia.com
      paths:
        - /
  tls:
    - secretName: api-ipcameras-aicacia-com-tls
      hosts:
        - api.aicacia.com

resources:
  requests:
    cpu: 80m
    memory: 128M
  limits:
    cpu: 250m
    memory: 512M
