/* tslint:disable */
/* eslint-disable */
/**
 * IPCameras API
 * IPCameras API API
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: nathanfaucett@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  Credentials,
  Errors,
  Token,
} from '../models/index';
import {
    CredentialsFromJSON,
    CredentialsToJSON,
    ErrorsFromJSON,
    ErrorsToJSON,
    TokenFromJSON,
    TokenToJSON,
} from '../models/index';

export interface TokenRequest {
    credentials: Credentials;
}

/**
 * TokenApi - interface
 * 
 * @export
 * @interface TokenApiInterface
 */
export interface TokenApiInterface {
    /**
     * 
     * @summary create a token by authenticating a user
     * @param {Credentials} credentials user credentials
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof TokenApiInterface
     */
    tokenRaw(requestParameters: TokenRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Token>>;

    /**
     * create a token by authenticating a user
     */
    token(credentials: Credentials, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Token>;

}

/**
 * 
 */
export class TokenApi extends runtime.BaseAPI implements TokenApiInterface {

    /**
     * create a token by authenticating a user
     */
    async tokenRaw(requestParameters: TokenRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Token>> {
        if (requestParameters['credentials'] == null) {
            throw new runtime.RequiredError(
                'credentials',
                'Required parameter "credentials" was null or undefined when calling token().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/token`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CredentialsToJSON(requestParameters['credentials']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => TokenFromJSON(jsonValue));
    }

    /**
     * create a token by authenticating a user
     */
    async token(credentials: Credentials, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Token> {
        const response = await this.tokenRaw({ credentials: credentials }, initOverrides);
        return await response.value();
    }

}
