name: Docker

on:
  workflow_run:
    workflows: ["Test"]
    branches: [main]
    types:
      - completed

jobs:
  docker:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: nathanfaucett@gmail.com
          password: ${{ secrets.GHCR_PASSWORD }}
      - name: API Build and Push
        uses: docker/build-push-action@v5
        with:
          context: ./api
          push: true
          tags: ghcr.io/aicacia/ipcameras-api:latest
      - name: UI Build and Push
        uses: docker/build-push-action@v5
        with:
          context: ./ui
          push: true
          tags: ghcr.io/aicacia/ipcameras-ui:latest
